stages:
  - deploy

deploy_frontend:
  stage: deploy
  tags:
    - frontend
  script:
    - cd /home/ubuntu/Attendence-project
    - git pull origin main
    - npm install
    - npm run build
    - pm2 restart all
  only:
    - main

deploy_backend:
  stage: deploy
  tags:
    - backend
  script:
    - cd /home/ubuntu/Attendence-project/backend
    - git pull origin main
    - npm install
    - pm2 restart all
  only:
    - main
