services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: attendance-backend
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongo:27017/attendance
      - PORT=5000
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongo-data: